### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by kennyjeffris** [AlakhaiVaynard/homebridge-vesync#13]
```
[7/17/2020, 07:25:35] [VesyncPlug] DeviceDiscovery invoked
(node:18893) UnhandledPromiseRejectionWarning: Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1474:34)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:917:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12)
(node:18893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by eugenet8k** [comment]
Same thing. Maybe there is a way to reset cache?

**Comment by jakesankey** [comment]
Had the same thing and all of my VeSync outlets went unresponsive in HomeKit. It seems the endpoint used in this plugin (server1.vesync.com...) cert is expired or no longer trusted. I was able to get things working again by adding the following environment var..

export NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by kennyjeffris** [comment]
I was able to get my plugs back up and running by switching to this fork: https://www.npmjs.com/package/homebridge-vesync-v2

**Comment by Gondee** [comment]
@kennyjeffris I still get that error on V2, @jakesankey can you comment on where to make that change?

**Comment by jakesankey** [comment]
I just added the export of that env var  to my bashrc file. 

Alternatively you could pass it as you start homebridge. 

ENV_VAR=value && homebridge

**Comment by bbernstein** [comment]
@kennyjeffris thanks for pointing to the working fork. For those who need instructions on how to switch to it. 

Simply uninstall the old and install the new one.
```
npm uninstall -g homebridge-vesync
npm install -g homebridge-vesync-v2
```
